/**
 * Static file server for the web build.
 *
 * A PWA cannot be tested from `file://` — service workers require a secure
 * context, which means https or localhost.
 *
 * `--https` serves over TLS using certs/ generated by make-lan-cert.mjs, which
 * is what makes the app installable from a phone on the same network. Plain
 * http works for playing, but the phone will not offer to install it and it
 * will not work with the laptop switched off.
 *
 * With --https a small companion server also listens on the http port. It
 * hands out the CA certificate at /ca.crt — the phone needs some way to fetch
 * that before it trusts anything — and redirects everything else to https.
 *
 * `--isolate` adds the cross-origin isolation headers that SharedArrayBuffer
 * needs, which is what would unlock a multi-threaded Stockfish in the browser.
 *
 * Usage:
 *   node scripts/serve.mjs [dir] [--port 8080] [--isolate]
 *   node scripts/serve.mjs [dir] --https [--port 8443] [--http-port 8080]
 */

import { createServer as createHttpServer } from 'node:http'
import { createServer as createHttpsServer } from 'node:https'
import { readFile, stat } from 'node:fs/promises'
import { readFileSync, existsSync } from 'node:fs'
import { join, extname, resolve, normalize } from 'node:path'
import { networkInterfaces } from 'node:os'

const args = process.argv.slice(2)
const dir = resolve(args.find((a) => !a.startsWith('--')) ?? 'dist-web')
const isolate = args.includes('--isolate')
const useHttps = args.includes('--https')

const flag = (name, fallback) => {
  const i = args.indexOf(name)
  return i >= 0 ? Number(args[i + 1]) : fallback
}
const port = flag('--port', useHttps ? 8443 : 8080)
const httpPort = flag('--http-port', 8080)

const CERT_DIR = resolve(process.cwd(), 'certs')

const TYPES = {
  '.html': 'text/html; charset=utf-8',
  '.js': 'text/javascript; charset=utf-8',
  '.mjs': 'text/javascript; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.json': 'application/json; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.png': 'image/png',
  '.ico': 'image/x-icon',
  '.wasm': 'application/wasm',
  '.webmanifest': 'application/manifest+json',
  '.woff2': 'font/woff2'
}

async function handle(req, res) {
  try {
    const url = new URL(req.url ?? '/', 'http://localhost')
    // Normalise before joining so `..` cannot escape the served directory.
    // URL paths always use forward slashes; strip leading ones before joining.
    const rel = normalize(decodeURIComponent(url.pathname)).replace(/^[/]+/, '')
    let file = join(dir, rel)
    if (!file.startsWith(dir)) {
      res.writeHead(403).end('Forbidden')
      return
    }

    let info = await stat(file).catch(() => null)
    if (info?.isDirectory()) {
      file = join(file, 'index.html')
      info = await stat(file).catch(() => null)
    }
    // Single-page app: unknown paths fall back to the shell.
    if (!info) {
      file = join(dir, 'index.html')
      info = await stat(file).catch(() => null)
      if (!info) {
        res.writeHead(404).end('Not found')
        return
      }
    }

    const body = await readFile(file)
    const headers = {
      'Content-Type': TYPES[extname(file).toLowerCase()] ?? 'application/octet-stream',
      'Content-Length': body.length,
      // No caching, so a rebuild is picked up without clearing site data.
      'Cache-Control': 'no-store'
    }
    if (isolate) {
      headers['Cross-Origin-Opener-Policy'] = 'same-origin'
      headers['Cross-Origin-Embedder-Policy'] = 'require-corp'
    }
    res.writeHead(200, headers).end(body)
  } catch (err) {
    res.writeHead(500).end(String(err))
  }
}

function lanAddresses() {
  return Object.values(networkInterfaces())
    .flat()
    .filter((a) => a && !a.internal && a.family === 'IPv4')
    .map((a) => a.address)
}

/**
 * The http side when running with TLS. It deliberately does not serve the app,
 * but it must serve the CA: the phone has no way to fetch the certificate over
 * a connection it does not yet trust.
 */
function startCompanionHttp(caPath) {
  const ca = readFileSync(caPath)
  const server = createHttpServer((req, res) => {
    const path = new URL(req.url ?? '/', 'http://localhost').pathname
    if (path === '/ca.crt' || path === '/ca') {
      res
        .writeHead(200, {
          // application/x-x509-ca-cert is what makes iOS hand this to the
          // profile installer. Deliberately no Content-Disposition: an
          // "attachment" makes Safari save it to Files instead, and the
          // install flow never starts.
          'Content-Type': 'application/x-x509-ca-cert',
          'Content-Length': ca.length
        })
        .end(ca)
      return
    }
    const host = (req.headers.host ?? '').split(':')[0]
    res.writeHead(302, { Location: `https://${host}:${port}${req.url}` }).end()
  })
  server.on('error', (err) => console.error(`http companion: ${err.message}`))
  server.listen(httpPort, '0.0.0.0')
  return server
}

if (useHttps) {
  const keyPath = join(CERT_DIR, 'server.key')
  const crtPath = join(CERT_DIR, 'server.crt')
  const caPath = join(CERT_DIR, 'ca.crt')

  if (!existsSync(keyPath) || !existsSync(crtPath)) {
    console.error('No certificate found. Run: node scripts/make-lan-cert.mjs')
    process.exit(1)
  }

  const server = createHttpsServer(
    { key: readFileSync(keyPath), cert: readFileSync(crtPath) },
    handle
  )

  server.listen(port, '0.0.0.0', () => {
    startCompanionHttp(caPath)
    console.log(`serving ${dir} over https\n`)
    console.log(`  https://localhost:${port}`)
    for (const a of lanAddresses()) console.log(`  https://${a}:${port}    <- open this on the phone`)
    console.log(`\n  certificate:  http://${lanAddresses()[0] ?? 'localhost'}:${httpPort}/ca.crt`)
    if (isolate) console.log('  cross-origin isolation: ON')
  })
} else {
  const server = createHttpServer(handle)
  server.listen(port, '0.0.0.0', () => {
    console.log(`serving ${dir}`)
    console.log(`  http://localhost:${port}`)
    for (const a of lanAddresses()) {
      console.log(`  http://${a}:${port}   (LAN — no service worker: not a secure context)`)
    }
    if (isolate) console.log('  cross-origin isolation: ON')
  })
}
